name: CI

on:
  push:
    branches:
      - main  # lub inna gałąź, na której chcesz uruchamiać workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t phpunit-php83 .

      - name: Run Composer Install
        run: |
          docker run -it --rm -v $(pwd):/app phpunit-php83 composer install

      - name: Run PHPUnit Tests
        run: |
          docker run -it --rm -v $(pwd):/app phpunit-php83 ./vendor/bin/phpunit tests/Domain/Entity/AMLMonitorTest.php